export const navMenu = [
  // {
  //   label: 'Visit',
  //   link: '/visit',
  //   children: [
  //     { label: 'Plan Your Visit', link: '/visit' },
  //     { label: 'Buy Tickets', link: '/tickets' },
  //     //{ label: 'Free Tour', link: '/free-tour' },
  //     //{ label: 'Guided Tours', link: '/guided-tours' },
  //     //{ label: 'School Visits', link: '/school-visits' },
  //     //{ label: 'Workshops', link: '/workshops' },
  //     //{ label: 'Museum Map', link: '/museum-map' },
  //     //   { label: 'Feedback', link: '/feedback' },
  //     //   { label: 'Contact', link: '/contact' },
  //   ],
  // },
  {
    label: 'Home',
    link: '/',
    children: [],
  },
  {
    label: 'Plan Your Visit',
    link: '/visit',
    children: [],
  },
  {
    label: 'Exhibitions & Events',
    link: '/exhibitions-events',
    children: [],
  },
  {
    label: 'Collections',
    //link: '/collections',
    children: [
      // { label: 'The KaramUniko Collections', link: '/collections' },
      { label: 'Why We’re Unique', link: '/collections/rare-stones' },
      { label: 'Crystal Gallery', link: '/collections/crystal' },

      { label: 'Rare Diamonds', link: '/collections/rare-stones' },
    ],
  },
  {
    label: 'About',
    link: '/about',
    children: [
      { label: 'Our Journey', link: '/karamuniko-museum-journey' },
      { label: 'Policies', link: '/policy' },
    ],
  },
  {
    label: 'Learn',
    link: '/learn',
    children: [
      { label: 'Learn with the Museum', link: '/learn-with-karamuniko-museum' },
      { label: 'Blog', link: '/blog' },
      { label: 'The KaramUniko Podcast', link: '/karamuniko-museum-podcast' },
      { label: 'Research At KaramUniko', link: '/research-at-karamuniko' },
    ],
  },
  {
    label: 'Auction',
    link: '/auction',
    children: [],
  },
]

export const treasuresOfNature = [
  {
    image: '/home/treasures/treasures1.png',
    title: 'Seven Trunk Ganesha',
    type: 'intro-with-bullets',
    description: [
      '<strong>Each of the seven trunks of this naturally formed Ganesha carries profound symbolic meaning — representing the eternal truth found in the sacred number seven, the rhythm through which the universe flows.</strong>',
      'Seven Chakras The energy centers within the human body — from root to crown — guiding physical, emotional, and spiritual awakening.',
      'Seven Days of the Week The cosmic cycle of time, reminding us that every moment is part of a divine rhythm.',
      'Seven Continents & Seven Seas The unity and wholeness of our planet — reflecting the oneness of creation.',
      //'Seven Rishis (Saptarishi) The ancient Vedic sages who illuminate the path of wisdom and dharma for humanity.',
      //'Seven Colors of the Rainbow The full spectrum of divine light — symbolizing purity, joy, and enlightenment.',
      //'Seven Musical Notes (Swaras) The foundation of universal sound and harmony — the music through which creation itself vibrates.',
    ],
  },
  {
    image: '/home/treasures/treasures2.png',
    title: 'Royal Bouquet Crystal',
    type: 'labeled-list',
    description: {
      intro:
        'A Natural Symphony of Elegance and Purity The Royal Bouquet Crystal blooms not from soil, but from the heart of the Earth itself. Each radiant rod of pure white crystal rises upward like a divine floral arrangement — a bouquet sculpted by nature’s unseen hands.',
      paragraphs: [
        'This breathtaking formation symbolizes unity, grace, and divine ascension — much like flowers reaching for the light.',
        //'Every glance at the Royal Bouquet Crystal feels like witnessing nature’s offering — a bouquet fit for royalty, formed over thousands of years without human touch.',
      ],
      fields: [
        { label: 'Origin', value: 'Earth’s natural mineral matrix' },
        { label: 'Formation', value: 'Naturally grown crystal cluster' },
        {
          label: 'Appearance',
          value:
            'Petal-like rods in luminous white hues, emerging from earthy brown matrix',
        },
        { label: 'Symbolism', value: 'Purity • Unity • Spiritual blooming' },
      ],
    },
  },
  {
    image: '/home/treasures/treasures3.png',
    title: 'Karam Earth’s Vision Specimen',
    type: 'paragraphs',
    description: [
      'This rare natural agate–quartz formation symbolizes the wondrous union of Earth and Light. The circular, eye-like patterns within it represent the Earth’s self-awareness — as if the planet itself is gazing at its own creation. Its earthy outer surface reflects the grounded essence of nature, while the translucent inner layers radiate light, consciousness, and beauty. This specimen stands as a breathtaking testament to nature’s artistry, depth, and creative intelligence.',
    ],
  },
]

export const visitMuseum = [
  {
    icon: '/home/visit-museum/image01.jpg',
    title: 'Plan Your Visit',
    description:
      'Discover essential information to make the most of your museum experience, including opening hours, ticket options, and visitor guidelines.',
    link: '/plan-your-visit',
  },
  {
    icon: '/home/visit-museum/image02.jpg',
    title: 'Museum Map',
    description:
      'Discover essential information to make the most of your museum experience, including opening hours, ticket options, and visitor guidelines.',
    link: '/plan-your-visit',
  },
  {
    icon: '/home/visit-museum/image03.png',
    title: 'Galleries',
    description:
      'Discover essential information to make the most of your museum experience, including opening hours, ticket options, and visitor guidelines.',
    link: '/plan-your-visit',
  },
  {
    icon: '/home/visit-museum/image01.jpg',
    title: 'Family Visit',
    description:
      'Discover essential information to make the most of your museum experience, including opening hours, ticket options, and visitor guidelines.',
    link: '/plan-your-visit',
  },
]

export const testimonials = [
  {
    id: 1,
    videoUrl: 'https://www.youtube.com/embed/XBdWVG9J7po',
    title: 'A Magical Experience',
    description:
      'Visiting KaramUniKO was like stepping into nature’s secret gallery. The gemstones here are untouched by human hands, yet they radiate more beauty than any crafted jewel. Truly a spiritual and eye-opening experience.',
    cta: 'Watch on YouTube →',
    youtubeLink: 'https://youtu.be/XBdWVG9J7po?si=DQqmEL8dmXmeuKnQ',
  },
  {
    id: 2,
    videoUrl: 'https://www.youtube.com/embed/PMWZh5KA-9A',
    title: 'Earth’s Rhythm',
    description:
      'Each crystal tells a story older than civilization itself — you can feel the Earth’s rhythm here.',
    cta: 'Watch on YouTube →',
    youtubeLink: 'https://youtu.be/PMWZh5KA-9A?si=XsjIfP193KP62Nkg',
  },
  {
    id: 3,
    videoUrl: 'https://www.youtube.com/embed/G5f7KPw0igQ',
    title: 'Unforgettable Energy',
    description:
      'The KaramUniKO experience connects you deeply with the planet’s creative energy — unforgettable.',
    cta: 'Watch on YouTube →',
    youtubeLink: 'https://youtu.be/G5f7KPw0igQ?si=NRve-70vowgRyrPa',
  },
  {
    id: 4,
    videoUrl: 'https://www.youtube.com/embed/09DnPh4k2Q8',
    title: 'Nature’s Artistry',
    description:
      'The artistry of nature is alive in every piece — breathtaking and humbling to witness.',
    cta: 'Watch on YouTube →',
    youtubeLink: 'https://youtu.be/09DnPh4k2Q8?si=pBMiyxbRdItwn7YH',
  },
  {
    id: 5,
    videoUrl: 'https://www.youtube.com/embed/O4uQallhdEY',
    title: 'Patience of Nature',
    description:
      'Each gem here speaks of patience — centuries of creation embodied in beauty and calm.',
    cta: 'Watch on YouTube →',
    youtubeLink: 'https://youtu.be/O4uQallhdEY?si=jzZ8_byAcHRpUlxk',
  },
  {
    id: 6,
    videoUrl: 'https://www.youtube.com/embed/Y5pl_sf-5PQ',
    title: 'Pure Craft of the Earth',
    description:
      'Nature’s craftsmanship cannot be replicated — KaramUniKO celebrates that truth perfectly.',
    cta: 'Watch on YouTube →',
    youtubeLink: 'https://youtu.be/Y5pl_sf-5PQ?si=Q_ZlwAlth46tvI5b',
  },
  {
    id: 7,
    videoUrl: 'https://www.youtube.com/embed/zDjGS6eXwe4',
    title: 'Unseen Beauty Revealed',
    description:
      'KaramUniKO reveals the unseen beauty within the Earth — a masterpiece of nature’s patience and perfection.',
    cta: 'Watch on YouTube →',
    youtubeLink: 'https://youtu.be/zDjGS6eXwe4?si=DihPmJq8rLl5SNw2',
  },
]

export const journey = [
  { image: '/journey/KGD (3).jpg' },
  { image: '/journey/KGD (4).jpg' },
  { image: '/journey/KGD (5).jpg' },
  { image: '/journey/KGD (6).jpg' },
  { image: '/journey/KGD (7).jpg' },
  { image: '/journey/KGD (8).jpg' },
  { image: '/journey/KGD (9).jpg' },
  { image: '/journey/KGD (10).jpg' },
  { image: '/journey/KGD (11).jpg' },
  { image: '/journey/KGD (12).jpg' },
  { image: '/journey/KGD (13).jpg' },
  { image: '/journey/KGD (14) A.jpg' },
  { image: '/journey/KGD (14).jpg' },
  { image: '/journey/KGD (15).jpg' },
  { image: '/journey/KGD (16).jpg' },
  { image: '/journey/KGD (17).jpg' },
  { image: '/journey/KGD (18).jpg' },
  { image: '/journey/KGD (19).jpg' },
  { image: '/journey/KGD (20).jpg' },
  { image: '/journey/KGD (21).jpg' },
  { image: '/journey/KGD (22).jpg' },
  { image: '/journey/KGD (23).jpg' },
  { image: '/journey/KGD (24).jpg' },
  { image: '/journey/KGD (25).jpg' },
  { image: '/journey/KGD (26).jpg' },
  { image: '/journey/KGD (27).jpg' },
  { image: '/journey/KGD (28).jpg' },
  { image: '/journey/KGD (29).jpg' },
  { image: '/journey/KGD (30).jpg' },
  { image: '/journey/KGD (31).jpg' },
  { image: '/journey/KGD (32).jpg' },
  { image: '/journey/KGD (33).jpg' },
  { image: '/journey/KGD (34).jpg' },
  { image: '/journey/KGD (35).jpg' },
  { image: '/journey/KGD (36).jpg' },
  { image: '/journey/KGD (37).jpg' },
  { image: '/journey/KGD (38).jpg' },
  { image: '/journey/KGD (39).jpg' },
  { image: '/journey/KGD (40).jpg' },
  { image: '/journey/KGD (41).jpg' },
  { image: '/journey/KGD (42).jpg' },
  { image: '/journey/KGD (43).jpg' },
  { image: '/journey/KGD (44).jpg' },
  { image: '/journey/KGD (45).jpg' },
  { image: '/journey/KGD (46).jpg' },
  { image: '/journey/KGD (46)A.jpg' },
  { image: '/journey/KGD (47).jpg' },
  { image: '/journey/KGD (47)B.jpg' },
  { image: '/journey/KGD (48).jpg' },
  { image: '/journey/KGD (49).jpg' },
  { image: '/journey/KGD (50).jpg' },
  { image: '/journey/KGD (51).jpg' },
  { image: '/journey/KGD (52).jpg' },
  { image: '/journey/KGD (53).jpg' },
  { image: '/journey/KGD (54).jpg' },
  { image: '/journey/KGD (55).jpg' },
  { image: '/journey/KGD (56).jpg' },
  { image: '/journey/KGD (57).jpg' },
  { image: '/journey/KGD (58).jpg' },
  { image: '/journey/KGD (59).jpg' },
  { image: '/journey/KGD (60).jpg' },
  { image: '/journey/KGD (61).jpg' },
  { image: '/journey/KGD (62).jpg' },
  { image: '/journey/KGD (63).jpg' },
  { image: '/journey/KGD (64).jpg' },
  { image: '/journey/KGD (65).jpg' },
  { image: '/journey/KGD (66).jpg' },
  { image: '/journey/KGD (67).jpg' },
  { image: '/journey/KGD (68).jpg' },
  { image: '/journey/KGD (69).jpg' },
  { image: '/journey/KGD (70).jpg' },
  { image: '/journey/KGD (71).jpg' },
  { image: '/journey/KGD (72).jpg' },
  { image: '/journey/KGD (73).jpg' },
  { image: '/journey/KGD (74).jpg' },
  { image: '/journey/KGD (75).jpg' },
  { image: '/journey/KGD (76).jpg' },
  { image: '/journey/KGD (77).jpg' },
  { image: '/journey/KGD (78).jpg' },
  { image: '/journey/KGD (79).jpg' },
  { image: '/journey/KGD (80).jpg' },
  { image: '/journey/KGD (81).jpg' },
  { image: '/journey/KGD (82).jpg' },
  { image: '/journey/KGD (83).jpg' },
  { image: '/journey/KGD (84).jpg' },
  { image: '/journey/KGD (85).jpg' },
  { image: '/journey/KGD (86).jpg' },
  { image: '/journey/KGD (87).jpg' },
  { image: '/journey/KGD (88).jpg' },
  { image: '/journey/KGD (89).jpg' },
  { image: '/journey/KGD (90).jpg' },
  { image: '/journey/thanks.jpg' },
]
